spring:
  application:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    
  redis:
    host: localhost
    jedis:
      pool:
        max-active: 2
        max-idle: 2
        min-idle: 1
    password: ''
    port: 6379
  session:
    redis:
      #flush-mode: 'on-save '
      namespace: 'spring:session '
      store-type: redis

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

jwt:
  secret: s3cr3t
  expiration: 10
   