spring:
  application:
    name: base-rest-api
    description: Demo REST API para Santander Mobile Banking Individuos
    version: 0.0.1-SNAPSHOT
    
  redis:
    host: localhost
    jedis:
      pool:
        max-active: 2
        max-idle: 2
        min-idle: 1
    password: ''
    port: 6379
  session:
    redis:
      #flush-mode: 'on-save '
      namespace: 'spring:session '
      store-type: redis

info:
  app:
    name: base-rest-api
    description: Demo REST API para Santander Mobile Banking Individuos
    version: 0.0.1-SNAPSHOT

jwt:
  secret: s3cr3t
  expiration: 10
   